package mmmi.se.sdu.dynamic;

final class RuntimeLoggerSmali {
	private RuntimeLoggerSmali() {
	}

	static String getContent() {
		return ".class public Lmmmi/se/sdu/dynamic/RuntimeLogger;\n"
				+ ".super Ljava/lang/Object;\n\n"

				// Store current context (activity/class name)
				+ ".field private static currentContext:Ljava/lang/String;\n\n"

				+ ".method public static setContext(Ljava/lang/String;)V\n"
				+ "    .locals 3\n"
				+ "    sput-object p0, Lmmmi/se/sdu/dynamic/RuntimeLogger;->currentContext:Ljava/lang/String;\n"
				+ "    const-string v0, \"IIFA-WebView-context\"\n"
				+ "    new-instance v1, Ljava/lang/StringBuilder;\n"
				+ "    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V\n"
				+ "    const-string v2, \"[Context: \"\n"
				+ "    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    invoke-virtual {v1, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    const-string v2, \"]\"\n"
				+ "    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n"
				+ "    move-result-object v1\n"
				+ "    invoke-static {v0, v1}, Landroid/util/Log;->i(Ljava/lang/String;Ljava/lang/String;)I\n"
				+ "    return-void\n"
				+ ".end method\n\n"

				+ ".method private static getContext()Ljava/lang/String;\n"
				+ "    .locals 1\n"
				+ "    sget-object v0, Lmmmi/se/sdu/dynamic/RuntimeLogger;->currentContext:Ljava/lang/String;\n"
				+ "    if-eqz v0, :ctx_null\n"
				+ "    return-object v0\n"
				+ ":ctx_null\n"
				+ "    const-string v0, \"unknown\"\n"
				+ "    return-object v0\n"
				+ ".end method\n\n"

				+ ".method public static logLoadUrl(Ljava/lang/String;)V\n"
				+ "    .locals 4\n"
				+ "    const-string v0, \"IIFA-WebView-loadUrl\"\n"
				+ "    invoke-static {}, Lmmmi/se/sdu/dynamic/RuntimeLogger;->getContext()Ljava/lang/String;\n"
				+ "    move-result-object v1\n"
				+ "    new-instance v2, Ljava/lang/StringBuilder;\n"
				+ "    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V\n"
				+ "    const-string v3, \"[Context: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    const-string v3, \"] URL: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    if-eqz p0, :loadurl_null\n"
				+ "    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    goto :loadurl_log\n"
				+ ":loadurl_null\n"
				+ "    const-string v3, \"null\"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ ":loadurl_log\n"
				+ "    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n"
				+ "    move-result-object v2\n"
				+ "    invoke-static {v0, v2}, Landroid/util/Log;->i(Ljava/lang/String;Ljava/lang/String;)I\n"
				+ "    return-void\n"
				+ ".end method\n\n"

				+ ".method public static logAddJavascriptInterface(Ljava/lang/String;Ljava/lang/Object;)V\n"
				+ "    .locals 4\n"
				+ "    const-string v0, \"IIFA-WebView-addJavascriptInterface\"\n"
				+ "    invoke-static {}, Lmmmi/se/sdu/dynamic/RuntimeLogger;->getContext()Ljava/lang/String;\n"
				+ "    move-result-object v1\n"
				+ "    new-instance v2, Ljava/lang/StringBuilder;\n"
				+ "    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V\n"
				+ "    const-string v3, \"[Context: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    const-string v3, \"] Interface: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    if-eqz p0, :interface_null\n"
				+ "    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    goto :append_bridge\n"
				+ ":interface_null\n"
				+ "    const-string v3, \"null\"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ ":append_bridge\n"
				+ "    const-string v3, \" Bridge: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    if-eqz p1, :bridge_null\n"
				+ "    invoke-virtual {p1}, Ljava/lang/Object;->getClass()Ljava/lang/Class;\n"
				+ "    move-result-object v3\n"
				+ "    invoke-virtual {v3}, Ljava/lang/Class;->getName()Ljava/lang/String;\n"
				+ "    move-result-object v3\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    goto :log_it\n"
				+ ":bridge_null\n"
				+ "    const-string v3, \"null\"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ ":log_it\n"
				+ "    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n"
				+ "    move-result-object v2\n"
				+ "    invoke-static {v0, v2}, Landroid/util/Log;->i(Ljava/lang/String;Ljava/lang/String;)I\n"
				+ "    return-void\n"
				+ ".end method\n\n"

				+ ".method public static logEvaluateJavascript(Ljava/lang/String;)V\n"
				+ "    .locals 4\n"
				+ "    const-string v0, \"IIFA-WebView-evaluateJavascript\"\n"
				+ "    invoke-static {}, Lmmmi/se/sdu/dynamic/RuntimeLogger;->getContext()Ljava/lang/String;\n"
				+ "    move-result-object v1\n"
				+ "    new-instance v2, Ljava/lang/StringBuilder;\n"
				+ "    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V\n"
				+ "    const-string v3, \"[Context: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    const-string v3, \"] JS: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    if-eqz p0, :eval_null\n"
				+ "    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    goto :eval_log\n"
				+ ":eval_null\n"
				+ "    const-string v3, \"null\"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ ":eval_log\n"
				+ "    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n"
				+ "    move-result-object v2\n"
				+ "    invoke-static {v0, v2}, Landroid/util/Log;->i(Ljava/lang/String;Ljava/lang/String;)I\n"
				+ "    return-void\n"
				+ ".end method\n\n"

				+ ".method public static logLoadData(Ljava/lang/String;)V\n"
				+ "    .locals 4\n"
				+ "    const-string v0, \"IIFA-WebView-loadData\"\n"
				+ "    invoke-static {}, Lmmmi/se/sdu/dynamic/RuntimeLogger;->getContext()Ljava/lang/String;\n"
				+ "    move-result-object v1\n"
				+ "    new-instance v2, Ljava/lang/StringBuilder;\n"
				+ "    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V\n"
				+ "    const-string v3, \"[Context: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    const-string v3, \"] Data: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    if-eqz p0, :loaddata_null\n"
				+ "    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    goto :loaddata_log\n"
				+ ":loaddata_null\n"
				+ "    const-string v3, \"null\"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ ":loaddata_log\n"
				+ "    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n"
				+ "    move-result-object v2\n"
				+ "    invoke-static {v0, v2}, Landroid/util/Log;->i(Ljava/lang/String;Ljava/lang/String;)I\n"
				+ "    return-void\n"
				+ ".end method\n\n"

				+ ".method public static logLoadDataWithBaseUrl(Ljava/lang/String;)V\n"
				+ "    .locals 4\n"
				+ "    const-string v0, \"IIFA-WebView-loadDataWithBaseURL\"\n"
				+ "    invoke-static {}, Lmmmi/se/sdu/dynamic/RuntimeLogger;->getContext()Ljava/lang/String;\n"
				+ "    move-result-object v1\n"
				+ "    new-instance v2, Ljava/lang/StringBuilder;\n"
				+ "    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V\n"
				+ "    const-string v3, \"[Context: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    const-string v3, \"] Data: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    if-eqz p0, :loaddatawb_null\n"
				+ "    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    goto :loaddatawb_log\n"
				+ ":loaddatawb_null\n"
				+ "    const-string v3, \"null\"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ ":loaddatawb_log\n"
				+ "    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n"
				+ "    move-result-object v2\n"
				+ "    invoke-static {v0, v2}, Landroid/util/Log;->i(Ljava/lang/String;Ljava/lang/String;)I\n"
				+ "    return-void\n"
				+ ".end method\n\n"

				+ ".method public static logPostUrl(Ljava/lang/String;)V\n"
				+ "    .locals 4\n"
				+ "    const-string v0, \"IIFA-WebView-postUrl\"\n"
				+ "    invoke-static {}, Lmmmi/se/sdu/dynamic/RuntimeLogger;->getContext()Ljava/lang/String;\n"
				+ "    move-result-object v1\n"
				+ "    new-instance v2, Ljava/lang/StringBuilder;\n"
				+ "    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V\n"
				+ "    const-string v3, \"[Context: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    const-string v3, \"] URL: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    if-eqz p0, :posturl_null\n"
				+ "    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    goto :posturl_log\n"
				+ ":posturl_null\n"
				+ "    const-string v3, \"null\"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ ":posturl_log\n"
				+ "    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n"
				+ "    move-result-object v2\n"
				+ "    invoke-static {v0, v2}, Landroid/util/Log;->i(Ljava/lang/String;Ljava/lang/String;)I\n"
				+ "    return-void\n"
				+ ".end method\n\n"

				+ ".method public static logLoadUrlStatic(Ljava/lang/String;)V\n"
				+ "    .locals 4\n"
				+ "    const-string v0, \"IIFA-WebView-loadUrl-STATIC\"\n"
				+ "    invoke-static {}, Lmmmi/se/sdu/dynamic/RuntimeLogger;->getContext()Ljava/lang/String;\n"
				+ "    move-result-object v1\n"
				+ "    new-instance v2, Ljava/lang/StringBuilder;\n"
				+ "    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V\n"
				+ "    const-string v3, \"[Context: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    const-string v3, \"] URL(static): \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    if-eqz p0, :loadurl_static_null\n"
				+ "    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    goto :loadurl_static_log\n"
				+ ":loadurl_static_null\n"
				+ "    const-string v3, \"null\"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ ":loadurl_static_log\n"
				+ "    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n"
				+ "    move-result-object v2\n"
				+ "    invoke-static {v0, v2}, Landroid/util/Log;->i(Ljava/lang/String;Ljava/lang/String;)I\n"
				+ "    return-void\n"
				+ ".end method\n"

				+ ".method public static logAddJavascriptInterfaceStatic(Ljava/lang/String;)V\n"
				+ "    .locals 4\n"
				+ "    const-string v0, \"IIFA-WebView-addJavascriptInterface-STATIC\"\n"
				+ "    invoke-static {}, Lmmmi/se/sdu/dynamic/RuntimeLogger;->getContext()Ljava/lang/String;\n"
				+ "    move-result-object v1\n"
				+ "    new-instance v2, Ljava/lang/StringBuilder;\n"
				+ "    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V\n"
				+ "    const-string v3, \"[Context: \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    const-string v3, \"] Interface(static): \"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    if-eqz p0, :iface_static_null\n"
				+ "    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ "    goto :iface_static_log\n"
				+ ":iface_static_null\n"
				+ "    const-string v3, \"null\"\n"
				+ "    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n"
				+ ":iface_static_log\n"
				+ "    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n"
				+ "    move-result-object v2\n"
				+ "    invoke-static {v0, v2}, Landroid/util/Log;->i(Ljava/lang/String;Ljava/lang/String;)I\n"
				+ "    return-void\n"
				+ ".end method\n";
	}
}

